### PR TITLE
task/JM-6680: Update utilisation_stats migration script

### PR DESCRIPTION
**Pull request by CCHAPMAN01**
### Jira link (if applicable)

https://centralgovernmentcgi.atlassian.net/browse/JM-6680

### Change description ###
- update utilisation_stats table migration script to:
  -  run inside a transaction
  - update the migration log 
  - follow run order naming convention

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines

Does this PR introduce a breaking change?
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ChrisWCGI** [comment]
I have a comment on the design of the table rather than the migration script itself.

Why have we kept the owner column when we also have the loc_code column?

**Comment by ChrisWCGI** [comment]
Another table design question ....

The new month_start column is defined as a timestamp but it will never have a time element in it. Shouldn't it just be a date?

**Comment by CCHAPMAN01** [comment]
> I have a comment on the design of the table rather than the migration script itself.
> 
> Why have we kept the owner column when we also have the loc_code column?

It's just been copied over 1:1 - my understanding is it is effectively a staging table for reports?

**Comment by CCHAPMAN01** [comment]
> Another table design question ....
> 
> The new month_start column is defined as a timestamp but it will never have a time element in it. Shouldn't it just be a date?

We can update the schema to reference date only - there will be no impact as it is not currently mapped to an entity/object and no tests have been written

**Comment by ChrisWCGI** [comment]
> > I have a comment on the design of the table rather than the migration script itself.
> > Why have we kept the owner column when we also have the loc_code column?
> 
> It's just been copied over 1:1 - my understanding is it is effectively a staging table for reports?

As we any table that had an owner column, we should have reviewed whether the owner column was needed and only kept it if it was.

I don't think it is needed. Agreed?
Is it too late to remove it?

**Comment by ChrisWCGI** [comment]
> > Another table design question ....
> > The new month_start column is defined as a timestamp but it will never have a time element in it. Shouldn't it just be a date?
> 
> We can update the schema to make it date only - there will be no impact as it is not currently mapped to an entity/object and no tests have been written

Agreed.

**Comment by CCHAPMAN01** [comment]
> > > I have a comment on the design of the table rather than the migration script itself.
> > > Why have we kept the owner column when we also have the loc_code column?
> > 
> > 
> > It's just been copied over 1:1 - my understanding is it is effectively a staging table for reports?
> 
> As we any table that had an owner column, we should have reviewed whether the owner column was needed and only kept it if it was.
> 
> I don't think it is needed. Agreed? Is it too late to remove it?

I will take your steer if it is not required we can remove it - currently there is no impact to the app or testing so now's still a good time to make changes 👍

**Review by ChrisWCGI — APPROVED** [review]

**Pull request merged**
